# Generated by Django 5.0.1 on 2024-02-11 12:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0002_alter_commentlike_comment_alter_commentlike_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='channel',
            name='banner',
            field=models.ImageField(blank=True, null=True, upload_to='pictures/channel-banner/'),
        ),
        migrations.AlterField(
            model_name='videocomment',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comment_children', to='content.videocomment'),
        ),
    ]
